version: '3'
services:
 web:
  image: nginx:alpine
  restart: always
  tty: true
  ports:
    - "${MYPORT2}:80"
  volumes:
    - ./code:/var/www
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
 
 db:
  image: postgres:alpine
  environment:
   - POSTGRES_USER=root
   - POSTGRES_PASSWORD=toor
   - POSTGRES_DB=blog
  ports:
   - "5432:5432"

 php:
  build:
   context: .
   dockerfile: ./dockers/php/Dockerfile
  volumes:
    - ./code:/var/www
    - ./php.ini:/etc/php7/conf.d/50-setting.ini
    - ./config/.env:/code/app/.env
    # - ./config/.env:/code/admin/.env
  env_file:
    - ./code/app/.env
  depends_on:
    - db