version: '3'
services:
 web:
  image: nginx:alpine
  restart: always
  tty: true
  ports:
    - "8080:80"
  volumes:
    - ./code:/var/www
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
 
 db:
  image: postgres:alpine
  environment:
   - POSTGRES_USER=root
   - POSTGRES_PASSWORD=toor
   - POSTGRES_DB=blog
  ports:
   - "5432:5432"

 php:
  build:
   context: .
   dockerfile: ./dockers/php/Dockerfile
   args:
    - UID=${UID}
  command: 
    ./app-init.sh
  volumes:
    - ./code:/var/www
    - ./.env-example:/var/www/app/.env
    - ./.env-example:/var/www/admin/.env
    - ./php.ini:/etc/php7/conf.d/50-setting.ini
  depends_on:
    - db